name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Check lint and test 
      run: ./gradlew lint testDebugUnitTestCoverage testReleaseUnitTestCoverage 
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: app/build/reports/jacoco/testDebugUnitTestCoverage/html/index.html
    - name: Archive test coverage results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: app/build/reports
